id: IE8BF8DD4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:29:34+00:00'
last_modified: '2022-06-08T02:26:15.794958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25548
  title: དུས་ཆེན་རིག་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4B9B:
      image_group_id: I1KG25550
      title: ''
      total_pages: 178
      order: 1
      base_file: 4B9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
