id: P004630
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:45:26.467729
source_metadata:
  id: bdr:W1KG25548
  title: དུས་ཆེན་རིག་གནས།
  author: ''
  volumes:
    85ee9a2cc1384cd3af13a9aa60317f11:
      image_group_id: I1KG25550
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
